version: '3'
services:
    #PHP Service
    laravel-broadcasting-app:
        build:
            context: ./docker/php
        container_name: laravel-broadcasting-app
        restart: unless-stopped
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - app-network
    #Nginx Service
    laravel-broadcasting-webserver:
        image: nginx:alpine
        container_name: laravel-broadcasting-webserver
        restart: unless-stopped
        depends_on:
            - laravel-broadcasting-app
            - laravel-broadcasting-redis
            - laravel-broadcasting-db
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
    #PgSql Service
    laravel-broadcasting-db:
        image: postgres
        container_name: laravel-broadcasting-db
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - '5432:5432'
        volumes:
            - laravel-broadcasting-data:/var/lib/postgresql/data
        networks:
            - app-network
    #Redis Service
    laravel-broadcasting-redis:
        image: redis:alpine
        container_name: laravel-broadcasting-redis
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
        volumes:
            - laravel-broadcasting-cache:/data
        networks:
            - app-network
#Docker Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    laravel-broadcasting-data:
        driver: local
    laravel-broadcasting-cache:
        driver: local
